### ISSUE TITLE
Can't start

### ISSUE THREAD

**Issue by hannesa2** [abhishekk06/sandbox#1]
I did a look on your sample (linked [here](https://github.com/google-ar/arcore-android-sdk/issues/1210#issuecomment-799943100))

I did some cleanup and moved to Android Studio 4.1. (3.6 was not able to start) and I run into this

<img width="1035" alt="image" src="https://user-images.githubusercontent.com/3314607/111271633-c44f8f80-8631-11eb-8e90-c21403320c26.png">

When you give me maintainer rights, I can push my branch

**Comment by abhishekk06** [comment]
Hi @hannesa2 ,

Thank you very much for helping me out. I have added you as my collaborator. 

Even I was hitting the same error after I did my last set of changes (not sure if I get past my last issue or there is something wrong in my implementation (i.e. moving from cameraX to arcore for creating bitmap))

**Comment by hannesa2** [comment]
Just for demonstration I made #2

**Comment by hannesa2** [comment]
Indeed revert in #2 "_deprecating cameraX API usage_" remove the `MISSING_GL_CONTEXT` error and make a black screen
