### ISSUE TITLE
surfaceView is null

### ISSUE THREAD

**Issue by hannesa2** [abhishekk06/sandbox#3]
You fail here
https://github.com/abhishekk06/sandbox/blob/7c4de37868429fcfe3346630f1a34562612f0283/app/src/main/java/com/android/example/camerax/tflite/CameraActivity.kt#L121

<img width="1305" alt="image" src="https://user-images.githubusercontent.com/3314607/111361162-d8c17580-868d-11eb-8b27-22cb91d18875.png">

because there is no assignment.

Of course it fails ! I miss a `surfaceView = foo()`

<img width="606" alt="image" src="https://user-images.githubusercontent.com/3314607/111361325-01e20600-868e-11eb-81fb-919c4feb1b1b.png">

**Comment by abhishekk06** [comment]
Ah ok, do I need to create a resource or something in layout.xml? TBH I am not sure how to use this. I assume ARCore will call it internally.

**Comment by abhishekk06** [comment]
ok, I added resource and assigned it a surface view and I am back to the same old issue :( 

![image](https://user-images.githubusercontent.com/55446334/111364430-95eca700-8667-11eb-9e75-15592b1dc0f1.png)


https://github.com/abhishekk06/sandbox/commit/3593b99e8a74ca8142ae5bf7f5dba3984a00a087

**Comment by abhishekk06** [comment]
>From your stack trace it looks like you're calling Session.update inside a callback. Callbacks usually run a different thread that the main one with the GL context.

The call to Session.update must happen on the thread that has the GL context. Suggest moving the call so that it does not happen inside the callback


@hannesa2 any idea how to do this?
